//
//  AirportSearchModels.swift
//  AirportFinder
//
//  Created by Savitha Rudramuni on 17/11/19.
//  Copyright (c) 2019 Savitha Rudramuni. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import CoreLocation

enum AirportSearch
{
  // MARK: Use cases
  
  enum Search
  {
    struct Request
    {
        let latitude:CLLocationDegrees = 0
        let longitude:CLLocationDegrees = 0
    }
    struct Response
    {
        let airports:[Airport]
    }
    struct ViewModel
    {
        let name:String
        let latitude:CLLocationDegrees = 0
        let longitude:CLLocationDegrees = 0
    }
  }
    
    enum NearBy
     {
       struct Request
       {
           let latitude:CLLocationDegrees
           let longitude:CLLocationDegrees
       }
        struct Response
       {
           var airports:[Airport]?
       }
       struct ViewModel
       {
           let name:String
           let latitude:CLLocationDegrees = 0
           let longitude:CLLocationDegrees = 0
       }
     }
}
